### ISSUE TITLE
dcat keyword error from geopython workshop

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeometa#177]
!pygeometa metadata generate ../data/countries.yml --schema dcat --output /tmp/countries.xml

throws:

Traceback (most recent call last):
  File "/usr/local/bin/pygeometa", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pygeometa/core.py", line 473, in generate
    content = schema_object.write(mcf_dict)
  File "/usr/local/lib/python3.10/dist-packages/pygeometa/schemas/dcat/__init__.py", line 177, in write
    dcat[k5].append(kw)
KeyError: 'keywords'

**Comment by ldesousa** [comment]
I can replicate this error with the `sample.yml` file (log below). This also means a test might be missing.

```
$ pygeometa metadata generate sample.yml --schema dcat --output /outputs/sample.json
Traceback (most recent call last):
  File "/home/duque004/git/pygeometa/env/bin/pygeometa", line 33, in <module>
    sys.exit(load_entry_point('pygeometa==0.11.1', 'console_scripts', 'pygeometa')())
  File "/home/duque004/git/pygeometa/env/lib/python3.10/site-packages/click-8.1.3-py3.10.egg/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/duque004/git/pygeometa/env/lib/python3.10/site-packages/click-8.1.3-py3.10.egg/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/duque004/git/pygeometa/env/lib/python3.10/site-packages/click-8.1.3-py3.10.egg/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/duque004/git/pygeometa/env/lib/python3.10/site-packages/click-8.1.3-py3.10.egg/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/duque004/git/pygeometa/env/lib/python3.10/site-packages/click-8.1.3-py3.10.egg/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/duque004/git/pygeometa/env/lib/python3.10/site-packages/click-8.1.3-py3.10.egg/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/duque004/git/pygeometa/env/lib/python3.10/site-packages/click-8.1.3-py3.10.egg/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/duque004/git/pygeometa/env/lib/python3.10/site-packages/pygeometa-0.11.1-py3.10.egg/pygeometa/core.py", line 474, in generate
    content = schema_object.write(mcf_dict)
  File "/home/duque004/git/pygeometa/env/lib/python3.10/site-packages/pygeometa-0.11.1-py3.10.egg/pygeometa/schemas/dcat/__init__.py", line 177, in write
    dcat[k5].append(kw)
KeyError: 'keywords'
```

**Comment by pvgenuchten** [comment]
Thanx @ldesousa
