### ISSUE TITLE
Error in using Transform function to convert iso19139 to wmo-wcmp2

### ISSUE THREAD

**Issue by ShaneMill1** [geopython/pygeometa#208]
We are using the metadata transform function to convert a iso19139 metadata record into wmo-wcmp2 using the following command.

pygeometa metadata transform metar-wis1-xmlformat --input-schema=iso19139 --output-schema=wmo-wcmp2

The error is:

  File "/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/pygeometa-0.13.1-py3.8.egg/pygeometa/schemas/ogcapi_records/__init__.py", line 127, in write
    begin = mcf['identification']['extents']['temporal'][0]['begin']
KeyError: 'begin'

[metar-wis1-xmlformat_txt.txt](https://github.com/geopython/pygeometa/files/10676416/metar-wis1-xmlformat_txt.txt)

We believe that line 345 may be causing the issue because the beginPosition is null, so the data is being treated as a continuous time series.

Because we are using the transform function, the metadata control file is being created for us, and looking for the begin position.

This seems to be related to #188 

@solson-nws

**Comment by tomkralidis** [comment]
@ShaneMill1 thanks for the report; I'm able to reproduce.

Are you able to test the below patch?

```diff
diff --git a/pygeometa/schemas/ogcapi_records/__init__.py b/pygeometa/schemas/ogcapi_records/__init__.py
index d0be753..a02eabc 100644
--- a/pygeometa/schemas/ogcapi_records/__init__.py
+++ b/pygeometa/schemas/ogcapi_records/__init__.py
@@ -123,7 +123,9 @@ class OGCAPIRecordOutputSchema(BaseOutputSchema):
         }
 
         LOGGER.debug('Checking for temporal')
-        if 'temporal' in mcf['identification']['extents']:
+        if all(['temporal' in mcf['identification']['extents'],
+                mcf['identification']['extents']['temporal'] != [{}]]):
+
             begin = mcf['identification']['extents']['temporal'][0]['begin']
             end = mcf['identification']['extents']['temporal'][0].get('end')
```

**Comment by ShaneMill1** [comment]
Hey @tomkralidis,

I made the modifications and reran:

(pygeometa-test) [shane.mill@ip-205-156-8-80 PygeoMeta-Investigation]$ pygeometa metadata transform metar-wis1-xmlformat --input-schema=iso19139 --output-schema=wmo-wcmp2

which returned:

/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/OWSLib-0.27.2-py3.8.egg/owslib/iso.py:120: FutureWarning: the .identification and .serviceidentification properties will merge into .identification being a list of properties.  This is currently implemented in .identificationinfo.  Please see https://github.com/geopython/OWSLib/issues/38 for more information
  warnings.warn(
/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/OWSLib-0.27.2-py3.8.egg/owslib/iso.py:596: FutureWarning: The .keywords and .keywords2 properties will merge into the .keywords property in the future, with .keywords becoming a list of MD_Keywords instances. This is currently implemented in .keywords2. Please see https://github.com/geopython/OWSLib/issues/301 for more information
  warnings.warn(
/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/OWSLib-0.27.2-py3.8.egg/owslib/iso.py:321: FutureWarning: The .keywords_object attribute will become .keywords proper in the next release. .keywords_object is a list of ibstances of the Keyword class. See for https://github.com/geopython/OWSLib/pull/765 more details.
  warnings.warn(
WMO Topic Hierarchy missing from MCF
Missing wmo:dataPolicy
Traceback (most recent call last):
  File "/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/pygeometa-0.13.1-py3.8.egg/pygeometa/schemas/wmo_wcmp2/__init__.py", line 105, in write
    record['properties']['wmo:dataPolicy'] = mcf['identification']['wmo_data_policy']  # noqa
KeyError: 'wmo_data_policy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shane.mill/mambaforge/envs/pygeometa-test/bin/pygeometa", line 33, in <module>
    sys.exit(load_entry_point('pygeometa==0.13.1', 'console_scripts', 'pygeometa')())
  File "/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/pygeometa-0.13.1-py3.8.egg/pygeometa/core.py", line 604, in transform
    content = schema_object_output.write(content)
  File "/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/pygeometa-0.13.1-py3.8.egg/pygeometa/schemas/wmo_wcmp2/__init__.py", line 109, in write
    raise RuntimeError(msg)
RuntimeError: Missing wmo:dataPolicy

I wonder if there are issues with the file I am testing. I was supplied another file:

[MD_urn_x-wmo_md_int.wmo.wis__ACUS58KOAX_20220404143452.txt](https://github.com/geopython/pygeometa/files/10687173/MD_urn_x-wmo_md_int.wmo.wis__ACUS58KOAX_20220404143452.txt)

This file actually gives a different error:

/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/OWSLib-0.27.2-py3.8.egg/owslib/iso.py:120: FutureWarning: the .identification and .serviceidentification properties will merge into .identification being a list of properties.  This is currently implemented in .identificationinfo.  Please see https://github.com/geopython/OWSLib/issues/38 for more information
  warnings.warn(
/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/OWSLib-0.27.2-py3.8.egg/owslib/iso.py:596: FutureWarning: The .keywords and .keywords2 properties will merge into the .keywords property in the future, with .keywords becoming a list of MD_Keywords instances. This is currently implemented in .keywords2. Please see https://github.com/geopython/OWSLib/issues/301 for more information
  warnings.warn(
/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/OWSLib-0.27.2-py3.8.egg/owslib/iso.py:321: FutureWarning: The .keywords_object attribute will become .keywords proper in the next release. .keywords_object is a list of ibstances of the Keyword class. See for https://github.com/geopython/OWSLib/pull/765 more details.
  warnings.warn(
Traceback (most recent call last):
  File "/home/shane.mill/mambaforge/envs/pygeometa-test/bin/pygeometa", line 33, in <module>
    sys.exit(load_entry_point('pygeometa==0.13.1', 'console_scripts', 'pygeometa')())
  File "/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/pygeometa-0.13.1-py3.8.egg/pygeometa/core.py", line 604, in transform
    content = schema_object_output.write(content)
  File "/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/pygeometa-0.13.1-py3.8.egg/pygeometa/schemas/wmo_wcmp2/__init__.py", line 83, in write
    record = super().write(mcf, stringify=False)
  File "/home/shane.mill/mambaforge/envs/pygeometa-test/lib/python3.8/site-packages/pygeometa-0.13.1-py3.8.egg/pygeometa/schemas/ogcapi_records/__init__.py", line 149, in write
    if 'creation' in mcf['identification']['dates']:
KeyError: 'dates'

I believe this error is more in line with the original error, in that they both are searching for a key that doesn't exist. I will use the latter file for now on for testing, because I suspect the first file I tested may not be compliant given the error.

**Comment by tomkralidis** [comment]
Thanks for the feedback @ShaneMill1.  #209 should fix the above issues (generating default metadata creation date, as well as throwing a warning instead of error on missing `wmo_data_policy`.  This should fix the issues based on your test cases in this issue.

Aside: having said this, while WCMP2 generation will throw some warnings on missing elements, this will still create the output WCMP2 record.  In the WIS2 context, you will need to add `wmo:topicHierarchy` and `wmo:dataPolicy` in accordance with the required elements of the standard to be able to validate against the WCMP2 schema proper.

**Comment by ShaneMill1** [comment]
Confirming this works! Thanks @tomkralidis!
