### ISSUE TITLE
error with pip install from source

### ISSUE THREAD

**Issue by bjamesvERT** [geopython/pygeometa#47]
Attempting to install pygeometa from source using pip fails, seemingly because setup.py imports 'pygeometa'.. the package which is to be built.

```bash
(test1)bjv@host:~$ pip install git+https://github.com/geopython/pygeometa.git#egg=pygeometa
You are using pip version 7.0.3, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pygeometa from git+https://github.com/geopython/pygeometa.git#egg=pygeometa
  Cloning https://github.com/geopython/pygeometa.git to /tmp/pip-build-sj02i_4c/pygeometa
p11-kit: invalid config filename, will be ignored in the future: /etc/pkcs11/modules/gnome-keyring-module
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-sj02i_4c/pygeometa/setup.py", line 53, in <module>
        import pygeometa
      File "/tmp/pip-build-sj02i_4c/pygeometa/pygeometa/__init__.py", line 52, in <module>
        from jinja2 import Environment, FileSystemLoader
    ImportError: No module named 'jinja2'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-sj02i_4c/pygeometa
```

**Comment by bjamesvERT** [comment]
pygeometa seems to be imported, only to get the module version info.

replacing import with regex as recommended by PyPA seems to fix the issue

(also, it's no longer necessary to manually preinstall dependencies via 'pip install -r requirements.txt' before running python setup.py build - after the self-import in setup.py is removed)
