### ISSUE TITLE
pygeometa self test fail

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/pygeometa#84]
Seems like [running pygeometa self tests](https://github.com/geopython/pygeometa#running-tests) fail after a fresh installation.

Beginning of the error message:
```
/my-env/pygeometa/tests$ python run_tests.py
__main__.PygeometaTest.test_get_charstring: Test support of unilingual or multilingual value(s)
.__main__.PygeometaTest.test_get_supported_schemas: Test supported schemas
.__main__.PygeometaTest.test_mcf_model: test mcf model and types
.__main__.PygeometaTest.test_nested_mcf: test nested mcf support
.__main__.PygeometaTest.test_pretty_print: Test pretty-printing
.__main__.PygeometaTest.test_read_mcf: Test reading MCFs, strings or dict
.__main__.PygeometaTest.test_render_template: test template rendering
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/__init__.py", line 978, in emit
    msg = self.format(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 828, in format
    return fmt.format(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 573, in format
    record.exc_text = self.formatException(record.exc_info)
  File "/usr/lib/python3.4/logging/__init__.py", line 523, in formatException
    traceback.print_exception(ei[0], ei[1], tb, None, sio)
  File "/usr/lib/python3.4/traceback.py", line 169, in print_exception
    for line in _format_exception_iter(etype, value, tb, limit, chain):
  File "/usr/lib/python3.4/traceback.py", line 146, in _format_exception_iter
    for value, tb in values:
  File "/usr/lib/python3.4/traceback.py", line 125, in _iter_chain
    context = exc.__context__
AttributeError: 'NoneType' object has no attribute '__context__'
```
Copying @RousseauLambertLP . Thanks!

**Comment by RousseauLambertLP** [comment]
After a discussion with @tomkralidis , these failures are normal. The tests are testing to produce some failures. 

And as we can see at the end of the test, Pygeometa tells us that the tests worked: 

```
----------------------------------------------------------------------
Ran 8 tests in 1.268s

OK
```

**Comment by alexandreleroux** [comment]
Thanks guys, what about changing the 'OK' ambiguous message in this context (given error messages precedes) to something clearer such as 'OK - Self tests completed successfully without error' or something like that? @tomkralidis @RousseauLambertLP

**Comment by tomkralidis** [comment]
@alexandreleroux the message outputs are standard Python `unittest` verbiage.  I'd rather not implement something custom given all we get with Python's testing support out of the box.  In addition, regardless of the output messages one can also check the status code (0=success) of the process.
